/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BooksSetListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheBooksSetListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheBooksSetListGenerated.onFilterBar().iCheckFilterField({ property: "title" });
            Then.onTheBooksSetListGenerated.onFilterBar().iCheckFilterField({ property: "author" });
            Then.onTheBooksSetListGenerated.onFilterBar().iCheckFilterField({ property: "price" });
            Then.onTheBooksSetListGenerated.onFilterBar().iCheckFilterField({ property: "gender" });
            Then.onTheBooksSetListGenerated.onFilterBar().iCheckFilterField({ property: "ageGroup" });
            Then.onTheBooksSetListGenerated.onFilterBar().iCheckFilterField({ property: "publishedDate" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheBooksSetListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheBooksSetListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheBooksSetListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheBooksSetListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"title":{"header":"Book Title"},"author":{"header":"Author"},"price":{"header":"Price"},"publishedDate":{"header":"Published Date"},"gender":{"header":"Gender"},"ageGroup":{"header":"Age Group"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheBooksSetListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheBooksSetListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheBooksSetListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheBooksSetObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});